package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/danehans/gofish/models"
)

// NewDoBootImageParams creates a new DoBootImageParams object
// with the default values initialized.
func NewDoBootImageParams() *DoBootImageParams {
	var ()
	return &DoBootImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDoBootImageParamsWithTimeout creates a new DoBootImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDoBootImageParamsWithTimeout(timeout time.Duration) *DoBootImageParams {
	var ()
	return &DoBootImageParams{

		timeout: timeout,
	}
}

// NewDoBootImageParamsWithContext creates a new DoBootImageParams object
// with the default values initialized, and the ability to set a context for a request
func NewDoBootImageParamsWithContext(ctx context.Context) *DoBootImageParams {
	var ()
	return &DoBootImageParams{

		Context: ctx,
	}
}

/*DoBootImageParams contains all the parameters to send to the API endpoint
for the do boot image operation typically these are written to a http.Request
*/
type DoBootImageParams struct {

	/*Identifier*/
	Identifier string
	/*Payload*/
	Payload *models.CIMCBootImageBootImage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the do boot image params
func (o *DoBootImageParams) WithTimeout(timeout time.Duration) *DoBootImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the do boot image params
func (o *DoBootImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the do boot image params
func (o *DoBootImageParams) WithContext(ctx context.Context) *DoBootImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the do boot image params
func (o *DoBootImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the do boot image params
func (o *DoBootImageParams) WithIdentifier(identifier string) *DoBootImageParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the do boot image params
func (o *DoBootImageParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WithPayload adds the payload to the do boot image params
func (o *DoBootImageParams) WithPayload(payload *models.CIMCBootImageBootImage) *DoBootImageParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the do boot image params
func (o *DoBootImageParams) SetPayload(payload *models.CIMCBootImageBootImage) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *DoBootImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if o.Payload == nil {
		o.Payload = new(models.CIMCBootImageBootImage)
	}

	if err := r.SetBodyParam(o.Payload); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
