package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDoLogoutSessionParams creates a new DoLogoutSessionParams object
// with the default values initialized.
func NewDoLogoutSessionParams() *DoLogoutSessionParams {
	var ()
	return &DoLogoutSessionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDoLogoutSessionParamsWithTimeout creates a new DoLogoutSessionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDoLogoutSessionParamsWithTimeout(timeout time.Duration) *DoLogoutSessionParams {
	var ()
	return &DoLogoutSessionParams{

		timeout: timeout,
	}
}

// NewDoLogoutSessionParamsWithContext creates a new DoLogoutSessionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDoLogoutSessionParamsWithContext(ctx context.Context) *DoLogoutSessionParams {
	var ()
	return &DoLogoutSessionParams{

		Context: ctx,
	}
}

/*DoLogoutSessionParams contains all the parameters to send to the API endpoint
for the do logout session operation typically these are written to a http.Request
*/
type DoLogoutSessionParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the do logout session params
func (o *DoLogoutSessionParams) WithTimeout(timeout time.Duration) *DoLogoutSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the do logout session params
func (o *DoLogoutSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the do logout session params
func (o *DoLogoutSessionParams) WithContext(ctx context.Context) *DoLogoutSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the do logout session params
func (o *DoLogoutSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the do logout session params
func (o *DoLogoutSessionParams) WithIdentifier(identifier string) *DoLogoutSessionParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the do logout session params
func (o *DoLogoutSessionParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *DoLogoutSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
