package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/danehans/gofish/models"
)

// NewDoResetParams creates a new DoResetParams object
// with the default values initialized.
func NewDoResetParams() *DoResetParams {
	var ()
	return &DoResetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDoResetParamsWithTimeout creates a new DoResetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDoResetParamsWithTimeout(timeout time.Duration) *DoResetParams {
	var ()
	return &DoResetParams{

		timeout: timeout,
	}
}

// NewDoResetParamsWithContext creates a new DoResetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDoResetParamsWithContext(ctx context.Context) *DoResetParams {
	var ()
	return &DoResetParams{

		Context: ctx,
	}
}

/*DoResetParams contains all the parameters to send to the API endpoint
for the do reset operation typically these are written to a http.Request
*/
type DoResetParams struct {

	/*Identifier*/
	Identifier string
	/*Payload*/
	Payload *models.CIMCResetActionResetAction

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the do reset params
func (o *DoResetParams) WithTimeout(timeout time.Duration) *DoResetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the do reset params
func (o *DoResetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the do reset params
func (o *DoResetParams) WithContext(ctx context.Context) *DoResetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the do reset params
func (o *DoResetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the do reset params
func (o *DoResetParams) WithIdentifier(identifier string) *DoResetParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the do reset params
func (o *DoResetParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WithPayload adds the payload to the do reset params
func (o *DoResetParams) WithPayload(payload *models.CIMCResetActionResetAction) *DoResetParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the do reset params
func (o *DoResetParams) SetPayload(payload *models.CIMCResetActionResetAction) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *DoResetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if o.Payload == nil {
		o.Payload = new(models.CIMCResetActionResetAction)
	}

	if err := r.SetBodyParam(o.Payload); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
