package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetManagerEthernetInterfaceParams creates a new GetManagerEthernetInterfaceParams object
// with the default values initialized.
func NewGetManagerEthernetInterfaceParams() *GetManagerEthernetInterfaceParams {
	var ()
	return &GetManagerEthernetInterfaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetManagerEthernetInterfaceParamsWithTimeout creates a new GetManagerEthernetInterfaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetManagerEthernetInterfaceParamsWithTimeout(timeout time.Duration) *GetManagerEthernetInterfaceParams {
	var ()
	return &GetManagerEthernetInterfaceParams{

		timeout: timeout,
	}
}

// NewGetManagerEthernetInterfaceParamsWithContext creates a new GetManagerEthernetInterfaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetManagerEthernetInterfaceParamsWithContext(ctx context.Context) *GetManagerEthernetInterfaceParams {
	var ()
	return &GetManagerEthernetInterfaceParams{

		Context: ctx,
	}
}

/*GetManagerEthernetInterfaceParams contains all the parameters to send to the API endpoint
for the get manager ethernet interface operation typically these are written to a http.Request
*/
type GetManagerEthernetInterfaceParams struct {

	/*Identifier*/
	Identifier string
	/*Index*/
	Index string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) WithTimeout(timeout time.Duration) *GetManagerEthernetInterfaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) WithContext(ctx context.Context) *GetManagerEthernetInterfaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) WithIdentifier(identifier string) *GetManagerEthernetInterfaceParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WithIndex adds the index to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) WithIndex(index string) *GetManagerEthernetInterfaceParams {
	o.SetIndex(index)
	return o
}

// SetIndex adds the index to the get manager ethernet interface params
func (o *GetManagerEthernetInterfaceParams) SetIndex(index string) {
	o.Index = index
}

// WriteToRequest writes these params to a swagger request
func (o *GetManagerEthernetInterfaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
