package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLocalEthernetInterfaceParams creates a new GetLocalEthernetInterfaceParams object
// with the default values initialized.
func NewGetLocalEthernetInterfaceParams() *GetLocalEthernetInterfaceParams {
	var ()
	return &GetLocalEthernetInterfaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLocalEthernetInterfaceParamsWithTimeout creates a new GetLocalEthernetInterfaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLocalEthernetInterfaceParamsWithTimeout(timeout time.Duration) *GetLocalEthernetInterfaceParams {
	var ()
	return &GetLocalEthernetInterfaceParams{

		timeout: timeout,
	}
}

// NewGetLocalEthernetInterfaceParamsWithContext creates a new GetLocalEthernetInterfaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLocalEthernetInterfaceParamsWithContext(ctx context.Context) *GetLocalEthernetInterfaceParams {
	var ()
	return &GetLocalEthernetInterfaceParams{

		Context: ctx,
	}
}

/*GetLocalEthernetInterfaceParams contains all the parameters to send to the API endpoint
for the get local ethernet interface operation typically these are written to a http.Request
*/
type GetLocalEthernetInterfaceParams struct {

	/*Index*/
	Index string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get local ethernet interface params
func (o *GetLocalEthernetInterfaceParams) WithTimeout(timeout time.Duration) *GetLocalEthernetInterfaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get local ethernet interface params
func (o *GetLocalEthernetInterfaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get local ethernet interface params
func (o *GetLocalEthernetInterfaceParams) WithContext(ctx context.Context) *GetLocalEthernetInterfaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get local ethernet interface params
func (o *GetLocalEthernetInterfaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIndex adds the index to the get local ethernet interface params
func (o *GetLocalEthernetInterfaceParams) WithIndex(index string) *GetLocalEthernetInterfaceParams {
	o.SetIndex(index)
	return o
}

// SetIndex adds the index to the get local ethernet interface params
func (o *GetLocalEthernetInterfaceParams) SetIndex(index string) {
	o.Index = index
}

// WriteToRequest writes these params to a swagger request
func (o *GetLocalEthernetInterfaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
