package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSelLogServiceEntryParams creates a new GetSelLogServiceEntryParams object
// with the default values initialized.
func NewGetSelLogServiceEntryParams() *GetSelLogServiceEntryParams {
	var ()
	return &GetSelLogServiceEntryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSelLogServiceEntryParamsWithTimeout creates a new GetSelLogServiceEntryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSelLogServiceEntryParamsWithTimeout(timeout time.Duration) *GetSelLogServiceEntryParams {
	var ()
	return &GetSelLogServiceEntryParams{

		timeout: timeout,
	}
}

// NewGetSelLogServiceEntryParamsWithContext creates a new GetSelLogServiceEntryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSelLogServiceEntryParamsWithContext(ctx context.Context) *GetSelLogServiceEntryParams {
	var ()
	return &GetSelLogServiceEntryParams{

		Context: ctx,
	}
}

/*GetSelLogServiceEntryParams contains all the parameters to send to the API endpoint
for the get sel log service entry operation typically these are written to a http.Request
*/
type GetSelLogServiceEntryParams struct {

	/*EntryID*/
	EntryID string
	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) WithTimeout(timeout time.Duration) *GetSelLogServiceEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) WithContext(ctx context.Context) *GetSelLogServiceEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithEntryID adds the entryID to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) WithEntryID(entryID string) *GetSelLogServiceEntryParams {
	o.SetEntryID(entryID)
	return o
}

// SetEntryID adds the entryId to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) SetEntryID(entryID string) {
	o.EntryID = entryID
}

// WithIdentifier adds the identifier to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) WithIdentifier(identifier string) *GetSelLogServiceEntryParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get sel log service entry params
func (o *GetSelLogServiceEntryParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetSelLogServiceEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param entryId
	if err := r.SetPathParam("entryId", o.EntryID); err != nil {
		return err
	}

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
