package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAccountServiceParams creates a new GetAccountServiceParams object
// with the default values initialized.
func NewGetAccountServiceParams() *GetAccountServiceParams {

	return &GetAccountServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountServiceParamsWithTimeout creates a new GetAccountServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAccountServiceParamsWithTimeout(timeout time.Duration) *GetAccountServiceParams {

	return &GetAccountServiceParams{

		timeout: timeout,
	}
}

// NewGetAccountServiceParamsWithContext creates a new GetAccountServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAccountServiceParamsWithContext(ctx context.Context) *GetAccountServiceParams {

	return &GetAccountServiceParams{

		Context: ctx,
	}
}

/*GetAccountServiceParams contains all the parameters to send to the API endpoint
for the get account service operation typically these are written to a http.Request
*/
type GetAccountServiceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get account service params
func (o *GetAccountServiceParams) WithTimeout(timeout time.Duration) *GetAccountServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account service params
func (o *GetAccountServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account service params
func (o *GetAccountServiceParams) WithContext(ctx context.Context) *GetAccountServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account service params
func (o *GetAccountServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
