package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSchemaParams creates a new GetSchemaParams object
// with the default values initialized.
func NewGetSchemaParams() *GetSchemaParams {
	var ()
	return &GetSchemaParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchemaParamsWithTimeout creates a new GetSchemaParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSchemaParamsWithTimeout(timeout time.Duration) *GetSchemaParams {
	var ()
	return &GetSchemaParams{

		timeout: timeout,
	}
}

// NewGetSchemaParamsWithContext creates a new GetSchemaParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSchemaParamsWithContext(ctx context.Context) *GetSchemaParams {
	var ()
	return &GetSchemaParams{

		Context: ctx,
	}
}

/*GetSchemaParams contains all the parameters to send to the API endpoint
for the get schema operation typically these are written to a http.Request
*/
type GetSchemaParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get schema params
func (o *GetSchemaParams) WithTimeout(timeout time.Duration) *GetSchemaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schema params
func (o *GetSchemaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schema params
func (o *GetSchemaParams) WithContext(ctx context.Context) *GetSchemaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schema params
func (o *GetSchemaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get schema params
func (o *GetSchemaParams) WithIdentifier(identifier string) *GetSchemaParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get schema params
func (o *GetSchemaParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
