package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetThermalParams creates a new GetThermalParams object
// with the default values initialized.
func NewGetThermalParams() *GetThermalParams {
	var ()
	return &GetThermalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetThermalParamsWithTimeout creates a new GetThermalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetThermalParamsWithTimeout(timeout time.Duration) *GetThermalParams {
	var ()
	return &GetThermalParams{

		timeout: timeout,
	}
}

// NewGetThermalParamsWithContext creates a new GetThermalParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetThermalParamsWithContext(ctx context.Context) *GetThermalParams {
	var ()
	return &GetThermalParams{

		Context: ctx,
	}
}

/*GetThermalParams contains all the parameters to send to the API endpoint
for the get thermal operation typically these are written to a http.Request
*/
type GetThermalParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get thermal params
func (o *GetThermalParams) WithTimeout(timeout time.Duration) *GetThermalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get thermal params
func (o *GetThermalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get thermal params
func (o *GetThermalParams) WithContext(ctx context.Context) *GetThermalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get thermal params
func (o *GetThermalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get thermal params
func (o *GetThermalParams) WithIdentifier(identifier string) *GetThermalParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get thermal params
func (o *GetThermalParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetThermalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
