package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRegistryFileParams creates a new GetRegistryFileParams object
// with the default values initialized.
func NewGetRegistryFileParams() *GetRegistryFileParams {
	var ()
	return &GetRegistryFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegistryFileParamsWithTimeout creates a new GetRegistryFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRegistryFileParamsWithTimeout(timeout time.Duration) *GetRegistryFileParams {
	var ()
	return &GetRegistryFileParams{

		timeout: timeout,
	}
}

// NewGetRegistryFileParamsWithContext creates a new GetRegistryFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRegistryFileParamsWithContext(ctx context.Context) *GetRegistryFileParams {
	var ()
	return &GetRegistryFileParams{

		Context: ctx,
	}
}

/*GetRegistryFileParams contains all the parameters to send to the API endpoint
for the get registry file operation typically these are written to a http.Request
*/
type GetRegistryFileParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get registry file params
func (o *GetRegistryFileParams) WithTimeout(timeout time.Duration) *GetRegistryFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get registry file params
func (o *GetRegistryFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get registry file params
func (o *GetRegistryFileParams) WithContext(ctx context.Context) *GetRegistryFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get registry file params
func (o *GetRegistryFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get registry file params
func (o *GetRegistryFileParams) WithIdentifier(identifier string) *GetRegistryFileParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get registry file params
func (o *GetRegistryFileParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegistryFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
