package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemTasksParams creates a new GetSystemTasksParams object
// with the default values initialized.
func NewGetSystemTasksParams() *GetSystemTasksParams {
	var ()
	return &GetSystemTasksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemTasksParamsWithTimeout creates a new GetSystemTasksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemTasksParamsWithTimeout(timeout time.Duration) *GetSystemTasksParams {
	var ()
	return &GetSystemTasksParams{

		timeout: timeout,
	}
}

// NewGetSystemTasksParamsWithContext creates a new GetSystemTasksParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemTasksParamsWithContext(ctx context.Context) *GetSystemTasksParams {
	var ()
	return &GetSystemTasksParams{

		Context: ctx,
	}
}

/*GetSystemTasksParams contains all the parameters to send to the API endpoint
for the get system tasks operation typically these are written to a http.Request
*/
type GetSystemTasksParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system tasks params
func (o *GetSystemTasksParams) WithTimeout(timeout time.Duration) *GetSystemTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system tasks params
func (o *GetSystemTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system tasks params
func (o *GetSystemTasksParams) WithContext(ctx context.Context) *GetSystemTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system tasks params
func (o *GetSystemTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get system tasks params
func (o *GetSystemTasksParams) WithIdentifier(identifier string) *GetSystemTasksParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get system tasks params
func (o *GetSystemTasksParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
