package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSessionServiceParams creates a new GetSessionServiceParams object
// with the default values initialized.
func NewGetSessionServiceParams() *GetSessionServiceParams {

	return &GetSessionServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSessionServiceParamsWithTimeout creates a new GetSessionServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSessionServiceParamsWithTimeout(timeout time.Duration) *GetSessionServiceParams {

	return &GetSessionServiceParams{

		timeout: timeout,
	}
}

// NewGetSessionServiceParamsWithContext creates a new GetSessionServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSessionServiceParamsWithContext(ctx context.Context) *GetSessionServiceParams {

	return &GetSessionServiceParams{

		Context: ctx,
	}
}

/*GetSessionServiceParams contains all the parameters to send to the API endpoint
for the get session service operation typically these are written to a http.Request
*/
type GetSessionServiceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get session service params
func (o *GetSessionServiceParams) WithTimeout(timeout time.Duration) *GetSessionServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get session service params
func (o *GetSessionServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get session service params
func (o *GetSessionServiceParams) WithContext(ctx context.Context) *GetSessionServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get session service params
func (o *GetSessionServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
