package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSessionInfoParams creates a new GetSessionInfoParams object
// with the default values initialized.
func NewGetSessionInfoParams() *GetSessionInfoParams {
	var ()
	return &GetSessionInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSessionInfoParamsWithTimeout creates a new GetSessionInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSessionInfoParamsWithTimeout(timeout time.Duration) *GetSessionInfoParams {
	var ()
	return &GetSessionInfoParams{

		timeout: timeout,
	}
}

// NewGetSessionInfoParamsWithContext creates a new GetSessionInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSessionInfoParamsWithContext(ctx context.Context) *GetSessionInfoParams {
	var ()
	return &GetSessionInfoParams{

		Context: ctx,
	}
}

/*GetSessionInfoParams contains all the parameters to send to the API endpoint
for the get session info operation typically these are written to a http.Request
*/
type GetSessionInfoParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get session info params
func (o *GetSessionInfoParams) WithTimeout(timeout time.Duration) *GetSessionInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get session info params
func (o *GetSessionInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get session info params
func (o *GetSessionInfoParams) WithContext(ctx context.Context) *GetSessionInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get session info params
func (o *GetSessionInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get session info params
func (o *GetSessionInfoParams) WithIdentifier(identifier string) *GetSessionInfoParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get session info params
func (o *GetSessionInfoParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
