package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSimpleStorageParams creates a new GetSimpleStorageParams object
// with the default values initialized.
func NewGetSimpleStorageParams() *GetSimpleStorageParams {
	var ()
	return &GetSimpleStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSimpleStorageParamsWithTimeout creates a new GetSimpleStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSimpleStorageParamsWithTimeout(timeout time.Duration) *GetSimpleStorageParams {
	var ()
	return &GetSimpleStorageParams{

		timeout: timeout,
	}
}

// NewGetSimpleStorageParamsWithContext creates a new GetSimpleStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSimpleStorageParamsWithContext(ctx context.Context) *GetSimpleStorageParams {
	var ()
	return &GetSimpleStorageParams{

		Context: ctx,
	}
}

/*GetSimpleStorageParams contains all the parameters to send to the API endpoint
for the get simple storage operation typically these are written to a http.Request
*/
type GetSimpleStorageParams struct {

	/*Identifier*/
	Identifier string
	/*Index*/
	Index string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get simple storage params
func (o *GetSimpleStorageParams) WithTimeout(timeout time.Duration) *GetSimpleStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get simple storage params
func (o *GetSimpleStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get simple storage params
func (o *GetSimpleStorageParams) WithContext(ctx context.Context) *GetSimpleStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get simple storage params
func (o *GetSimpleStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get simple storage params
func (o *GetSimpleStorageParams) WithIdentifier(identifier string) *GetSimpleStorageParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get simple storage params
func (o *GetSimpleStorageParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WithIndex adds the index to the get simple storage params
func (o *GetSimpleStorageParams) WithIndex(index string) *GetSimpleStorageParams {
	o.SetIndex(index)
	return o
}

// SetIndex adds the index to the get simple storage params
func (o *GetSimpleStorageParams) SetIndex(index string) {
	o.Index = index
}

// WriteToRequest writes these params to a swagger request
func (o *GetSimpleStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
