package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetManagerParams creates a new GetManagerParams object
// with the default values initialized.
func NewGetManagerParams() *GetManagerParams {
	var ()
	return &GetManagerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetManagerParamsWithTimeout creates a new GetManagerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetManagerParamsWithTimeout(timeout time.Duration) *GetManagerParams {
	var ()
	return &GetManagerParams{

		timeout: timeout,
	}
}

// NewGetManagerParamsWithContext creates a new GetManagerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetManagerParamsWithContext(ctx context.Context) *GetManagerParams {
	var ()
	return &GetManagerParams{

		Context: ctx,
	}
}

/*GetManagerParams contains all the parameters to send to the API endpoint
for the get manager operation typically these are written to a http.Request
*/
type GetManagerParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get manager params
func (o *GetManagerParams) WithTimeout(timeout time.Duration) *GetManagerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get manager params
func (o *GetManagerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get manager params
func (o *GetManagerParams) WithContext(ctx context.Context) *GetManagerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get manager params
func (o *GetManagerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get manager params
func (o *GetManagerParams) WithIdentifier(identifier string) *GetManagerParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get manager params
func (o *GetManagerParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetManagerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
