package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRegistryFileContentsParams creates a new GetRegistryFileContentsParams object
// with the default values initialized.
func NewGetRegistryFileContentsParams() *GetRegistryFileContentsParams {
	var ()
	return &GetRegistryFileContentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegistryFileContentsParamsWithTimeout creates a new GetRegistryFileContentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRegistryFileContentsParamsWithTimeout(timeout time.Duration) *GetRegistryFileContentsParams {
	var ()
	return &GetRegistryFileContentsParams{

		timeout: timeout,
	}
}

// NewGetRegistryFileContentsParamsWithContext creates a new GetRegistryFileContentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRegistryFileContentsParamsWithContext(ctx context.Context) *GetRegistryFileContentsParams {
	var ()
	return &GetRegistryFileContentsParams{

		Context: ctx,
	}
}

/*GetRegistryFileContentsParams contains all the parameters to send to the API endpoint
for the get registry file contents operation typically these are written to a http.Request
*/
type GetRegistryFileContentsParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get registry file contents params
func (o *GetRegistryFileContentsParams) WithTimeout(timeout time.Duration) *GetRegistryFileContentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get registry file contents params
func (o *GetRegistryFileContentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get registry file contents params
func (o *GetRegistryFileContentsParams) WithContext(ctx context.Context) *GetRegistryFileContentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get registry file contents params
func (o *GetRegistryFileContentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the get registry file contents params
func (o *GetRegistryFileContentsParams) WithIdentifier(identifier string) *GetRegistryFileContentsParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the get registry file contents params
func (o *GetRegistryFileContentsParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegistryFileContentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
