package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListSystemProcessorsParams creates a new ListSystemProcessorsParams object
// with the default values initialized.
func NewListSystemProcessorsParams() *ListSystemProcessorsParams {
	var ()
	return &ListSystemProcessorsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSystemProcessorsParamsWithTimeout creates a new ListSystemProcessorsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSystemProcessorsParamsWithTimeout(timeout time.Duration) *ListSystemProcessorsParams {
	var ()
	return &ListSystemProcessorsParams{

		timeout: timeout,
	}
}

// NewListSystemProcessorsParamsWithContext creates a new ListSystemProcessorsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSystemProcessorsParamsWithContext(ctx context.Context) *ListSystemProcessorsParams {
	var ()
	return &ListSystemProcessorsParams{

		Context: ctx,
	}
}

/*ListSystemProcessorsParams contains all the parameters to send to the API endpoint
for the list system processors operation typically these are written to a http.Request
*/
type ListSystemProcessorsParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list system processors params
func (o *ListSystemProcessorsParams) WithTimeout(timeout time.Duration) *ListSystemProcessorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list system processors params
func (o *ListSystemProcessorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list system processors params
func (o *ListSystemProcessorsParams) WithContext(ctx context.Context) *ListSystemProcessorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list system processors params
func (o *ListSystemProcessorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the list system processors params
func (o *ListSystemProcessorsParams) WithIdentifier(identifier string) *ListSystemProcessorsParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the list system processors params
func (o *ListSystemProcessorsParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *ListSystemProcessorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
