package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListManagerEthernetInterfacesParams creates a new ListManagerEthernetInterfacesParams object
// with the default values initialized.
func NewListManagerEthernetInterfacesParams() *ListManagerEthernetInterfacesParams {
	var ()
	return &ListManagerEthernetInterfacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListManagerEthernetInterfacesParamsWithTimeout creates a new ListManagerEthernetInterfacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListManagerEthernetInterfacesParamsWithTimeout(timeout time.Duration) *ListManagerEthernetInterfacesParams {
	var ()
	return &ListManagerEthernetInterfacesParams{

		timeout: timeout,
	}
}

// NewListManagerEthernetInterfacesParamsWithContext creates a new ListManagerEthernetInterfacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListManagerEthernetInterfacesParamsWithContext(ctx context.Context) *ListManagerEthernetInterfacesParams {
	var ()
	return &ListManagerEthernetInterfacesParams{

		Context: ctx,
	}
}

/*ListManagerEthernetInterfacesParams contains all the parameters to send to the API endpoint
for the list manager ethernet interfaces operation typically these are written to a http.Request
*/
type ListManagerEthernetInterfacesParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list manager ethernet interfaces params
func (o *ListManagerEthernetInterfacesParams) WithTimeout(timeout time.Duration) *ListManagerEthernetInterfacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list manager ethernet interfaces params
func (o *ListManagerEthernetInterfacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list manager ethernet interfaces params
func (o *ListManagerEthernetInterfacesParams) WithContext(ctx context.Context) *ListManagerEthernetInterfacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list manager ethernet interfaces params
func (o *ListManagerEthernetInterfacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the list manager ethernet interfaces params
func (o *ListManagerEthernetInterfacesParams) WithIdentifier(identifier string) *ListManagerEthernetInterfacesParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the list manager ethernet interfaces params
func (o *ListManagerEthernetInterfacesParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *ListManagerEthernetInterfacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
