package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListBootImageParams creates a new ListBootImageParams object
// with the default values initialized.
func NewListBootImageParams() *ListBootImageParams {
	var ()
	return &ListBootImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListBootImageParamsWithTimeout creates a new ListBootImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListBootImageParamsWithTimeout(timeout time.Duration) *ListBootImageParams {
	var ()
	return &ListBootImageParams{

		timeout: timeout,
	}
}

// NewListBootImageParamsWithContext creates a new ListBootImageParams object
// with the default values initialized, and the ability to set a context for a request
func NewListBootImageParamsWithContext(ctx context.Context) *ListBootImageParams {
	var ()
	return &ListBootImageParams{

		Context: ctx,
	}
}

/*ListBootImageParams contains all the parameters to send to the API endpoint
for the list boot image operation typically these are written to a http.Request
*/
type ListBootImageParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list boot image params
func (o *ListBootImageParams) WithTimeout(timeout time.Duration) *ListBootImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list boot image params
func (o *ListBootImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list boot image params
func (o *ListBootImageParams) WithContext(ctx context.Context) *ListBootImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list boot image params
func (o *ListBootImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the list boot image params
func (o *ListBootImageParams) WithIdentifier(identifier string) *ListBootImageParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the list boot image params
func (o *ListBootImageParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *ListBootImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
