package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListSchemasParams creates a new ListSchemasParams object
// with the default values initialized.
func NewListSchemasParams() *ListSchemasParams {

	return &ListSchemasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSchemasParamsWithTimeout creates a new ListSchemasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSchemasParamsWithTimeout(timeout time.Duration) *ListSchemasParams {

	return &ListSchemasParams{

		timeout: timeout,
	}
}

// NewListSchemasParamsWithContext creates a new ListSchemasParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSchemasParamsWithContext(ctx context.Context) *ListSchemasParams {

	return &ListSchemasParams{

		Context: ctx,
	}
}

/*ListSchemasParams contains all the parameters to send to the API endpoint
for the list schemas operation typically these are written to a http.Request
*/
type ListSchemasParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list schemas params
func (o *ListSchemasParams) WithTimeout(timeout time.Duration) *ListSchemasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list schemas params
func (o *ListSchemasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list schemas params
func (o *ListSchemasParams) WithContext(ctx context.Context) *ListSchemasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list schemas params
func (o *ListSchemasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *ListSchemasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
