package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListManagersParams creates a new ListManagersParams object
// with the default values initialized.
func NewListManagersParams() *ListManagersParams {

	return &ListManagersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListManagersParamsWithTimeout creates a new ListManagersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListManagersParamsWithTimeout(timeout time.Duration) *ListManagersParams {

	return &ListManagersParams{

		timeout: timeout,
	}
}

// NewListManagersParamsWithContext creates a new ListManagersParams object
// with the default values initialized, and the ability to set a context for a request
func NewListManagersParamsWithContext(ctx context.Context) *ListManagersParams {

	return &ListManagersParams{

		Context: ctx,
	}
}

/*ListManagersParams contains all the parameters to send to the API endpoint
for the list managers operation typically these are written to a http.Request
*/
type ListManagersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list managers params
func (o *ListManagersParams) WithTimeout(timeout time.Duration) *ListManagersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list managers params
func (o *ListManagersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list managers params
func (o *ListManagersParams) WithContext(ctx context.Context) *ListManagersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list managers params
func (o *ListManagersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *ListManagersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
