package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListSelLogServiceEntriesParams creates a new ListSelLogServiceEntriesParams object
// with the default values initialized.
func NewListSelLogServiceEntriesParams() *ListSelLogServiceEntriesParams {
	var ()
	return &ListSelLogServiceEntriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSelLogServiceEntriesParamsWithTimeout creates a new ListSelLogServiceEntriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSelLogServiceEntriesParamsWithTimeout(timeout time.Duration) *ListSelLogServiceEntriesParams {
	var ()
	return &ListSelLogServiceEntriesParams{

		timeout: timeout,
	}
}

// NewListSelLogServiceEntriesParamsWithContext creates a new ListSelLogServiceEntriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSelLogServiceEntriesParamsWithContext(ctx context.Context) *ListSelLogServiceEntriesParams {
	var ()
	return &ListSelLogServiceEntriesParams{

		Context: ctx,
	}
}

/*ListSelLogServiceEntriesParams contains all the parameters to send to the API endpoint
for the list sel log service entries operation typically these are written to a http.Request
*/
type ListSelLogServiceEntriesParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list sel log service entries params
func (o *ListSelLogServiceEntriesParams) WithTimeout(timeout time.Duration) *ListSelLogServiceEntriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list sel log service entries params
func (o *ListSelLogServiceEntriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list sel log service entries params
func (o *ListSelLogServiceEntriesParams) WithContext(ctx context.Context) *ListSelLogServiceEntriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list sel log service entries params
func (o *ListSelLogServiceEntriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the list sel log service entries params
func (o *ListSelLogServiceEntriesParams) WithIdentifier(identifier string) *ListSelLogServiceEntriesParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the list sel log service entries params
func (o *ListSelLogServiceEntriesParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *ListSelLogServiceEntriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
