package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListSimpleStorageParams creates a new ListSimpleStorageParams object
// with the default values initialized.
func NewListSimpleStorageParams() *ListSimpleStorageParams {
	var ()
	return &ListSimpleStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSimpleStorageParamsWithTimeout creates a new ListSimpleStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSimpleStorageParamsWithTimeout(timeout time.Duration) *ListSimpleStorageParams {
	var ()
	return &ListSimpleStorageParams{

		timeout: timeout,
	}
}

// NewListSimpleStorageParamsWithContext creates a new ListSimpleStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSimpleStorageParamsWithContext(ctx context.Context) *ListSimpleStorageParams {
	var ()
	return &ListSimpleStorageParams{

		Context: ctx,
	}
}

/*ListSimpleStorageParams contains all the parameters to send to the API endpoint
for the list simple storage operation typically these are written to a http.Request
*/
type ListSimpleStorageParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list simple storage params
func (o *ListSimpleStorageParams) WithTimeout(timeout time.Duration) *ListSimpleStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list simple storage params
func (o *ListSimpleStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list simple storage params
func (o *ListSimpleStorageParams) WithContext(ctx context.Context) *ListSimpleStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list simple storage params
func (o *ListSimpleStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the list simple storage params
func (o *ListSimpleStorageParams) WithIdentifier(identifier string) *ListSimpleStorageParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the list simple storage params
func (o *ListSimpleStorageParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *ListSimpleStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
