package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListLogServiceParams creates a new ListLogServiceParams object
// with the default values initialized.
func NewListLogServiceParams() *ListLogServiceParams {
	var ()
	return &ListLogServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListLogServiceParamsWithTimeout creates a new ListLogServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListLogServiceParamsWithTimeout(timeout time.Duration) *ListLogServiceParams {
	var ()
	return &ListLogServiceParams{

		timeout: timeout,
	}
}

// NewListLogServiceParamsWithContext creates a new ListLogServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewListLogServiceParamsWithContext(ctx context.Context) *ListLogServiceParams {
	var ()
	return &ListLogServiceParams{

		Context: ctx,
	}
}

/*ListLogServiceParams contains all the parameters to send to the API endpoint
for the list log service operation typically these are written to a http.Request
*/
type ListLogServiceParams struct {

	/*Identifier*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list log service params
func (o *ListLogServiceParams) WithTimeout(timeout time.Duration) *ListLogServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list log service params
func (o *ListLogServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list log service params
func (o *ListLogServiceParams) WithContext(ctx context.Context) *ListLogServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list log service params
func (o *ListLogServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the list log service params
func (o *ListLogServiceParams) WithIdentifier(identifier string) *ListLogServiceParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the list log service params
func (o *ListLogServiceParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *ListLogServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
