package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRemoveAccountParams creates a new RemoveAccountParams object
// with the default values initialized.
func NewRemoveAccountParams() *RemoveAccountParams {
	var ()
	return &RemoveAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveAccountParamsWithTimeout creates a new RemoveAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveAccountParamsWithTimeout(timeout time.Duration) *RemoveAccountParams {
	var ()
	return &RemoveAccountParams{

		timeout: timeout,
	}
}

// NewRemoveAccountParamsWithContext creates a new RemoveAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveAccountParamsWithContext(ctx context.Context) *RemoveAccountParams {
	var ()
	return &RemoveAccountParams{

		Context: ctx,
	}
}

/*RemoveAccountParams contains all the parameters to send to the API endpoint
for the remove account operation typically these are written to a http.Request
*/
type RemoveAccountParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove account params
func (o *RemoveAccountParams) WithTimeout(timeout time.Duration) *RemoveAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove account params
func (o *RemoveAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove account params
func (o *RemoveAccountParams) WithContext(ctx context.Context) *RemoveAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove account params
func (o *RemoveAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithName adds the name to the remove account params
func (o *RemoveAccountParams) WithName(name string) *RemoveAccountParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the remove account params
func (o *RemoveAccountParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
