package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTaskServiceRootParams creates a new TaskServiceRootParams object
// with the default values initialized.
func NewTaskServiceRootParams() *TaskServiceRootParams {

	return &TaskServiceRootParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTaskServiceRootParamsWithTimeout creates a new TaskServiceRootParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTaskServiceRootParamsWithTimeout(timeout time.Duration) *TaskServiceRootParams {

	return &TaskServiceRootParams{

		timeout: timeout,
	}
}

// NewTaskServiceRootParamsWithContext creates a new TaskServiceRootParams object
// with the default values initialized, and the ability to set a context for a request
func NewTaskServiceRootParamsWithContext(ctx context.Context) *TaskServiceRootParams {

	return &TaskServiceRootParams{

		Context: ctx,
	}
}

/*TaskServiceRootParams contains all the parameters to send to the API endpoint
for the task service root operation typically these are written to a http.Request
*/
type TaskServiceRootParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the task service root params
func (o *TaskServiceRootParams) WithTimeout(timeout time.Duration) *TaskServiceRootParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the task service root params
func (o *TaskServiceRootParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the task service root params
func (o *TaskServiceRootParams) WithContext(ctx context.Context) *TaskServiceRootParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the task service root params
func (o *TaskServiceRootParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *TaskServiceRootParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
