package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/danehans/gofish/models"
)

// NewTestEventParams creates a new TestEventParams object
// with the default values initialized.
func NewTestEventParams() *TestEventParams {
	var ()
	return &TestEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestEventParamsWithTimeout creates a new TestEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestEventParamsWithTimeout(timeout time.Duration) *TestEventParams {
	var ()
	return &TestEventParams{

		timeout: timeout,
	}
}

// NewTestEventParamsWithContext creates a new TestEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewTestEventParamsWithContext(ctx context.Context) *TestEventParams {
	var ()
	return &TestEventParams{

		Context: ctx,
	}
}

/*TestEventParams contains all the parameters to send to the API endpoint
for the test event operation typically these are written to a http.Request
*/
type TestEventParams struct {

	/*Body*/
	Body models.TestEvent

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the test event params
func (o *TestEventParams) WithTimeout(timeout time.Duration) *TestEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test event params
func (o *TestEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test event params
func (o *TestEventParams) WithContext(ctx context.Context) *TestEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test event params
func (o *TestEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the test event params
func (o *TestEventParams) WithBody(body models.TestEvent) *TestEventParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the test event params
func (o *TestEventParams) SetBody(body models.TestEvent) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TestEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
