package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnimplementedParams creates a new UnimplementedParams object
// with the default values initialized.
func NewUnimplementedParams() *UnimplementedParams {
	var ()
	return &UnimplementedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnimplementedParamsWithTimeout creates a new UnimplementedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnimplementedParamsWithTimeout(timeout time.Duration) *UnimplementedParams {
	var ()
	return &UnimplementedParams{

		timeout: timeout,
	}
}

// NewUnimplementedParamsWithContext creates a new UnimplementedParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnimplementedParamsWithContext(ctx context.Context) *UnimplementedParams {
	var ()
	return &UnimplementedParams{

		Context: ctx,
	}
}

/*UnimplementedParams contains all the parameters to send to the API endpoint
for the unimplemented operation typically these are written to a http.Request
*/
type UnimplementedParams struct {

	/*Identifier*/
	Identifier string
	/*Index*/
	Index string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unimplemented params
func (o *UnimplementedParams) WithTimeout(timeout time.Duration) *UnimplementedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unimplemented params
func (o *UnimplementedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unimplemented params
func (o *UnimplementedParams) WithContext(ctx context.Context) *UnimplementedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unimplemented params
func (o *UnimplementedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithIdentifier adds the identifier to the unimplemented params
func (o *UnimplementedParams) WithIdentifier(identifier string) *UnimplementedParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the unimplemented params
func (o *UnimplementedParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WithIndex adds the index to the unimplemented params
func (o *UnimplementedParams) WithIndex(index string) *UnimplementedParams {
	o.SetIndex(index)
	return o
}

// SetIndex adds the index to the unimplemented params
func (o *UnimplementedParams) SetIndex(index string) {
	o.Index = index
}

// WriteToRequest writes these params to a swagger request
func (o *UnimplementedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
